
services:
  web:
    depends_on:
      - db
    restart: always
    build: ./top10-github
    command: python -m flask --app top10 run --host=0.0.0.0
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
  angular:
    build: ./frontend
    ports:
      - 4200:80
    depends_on:
      - web
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - angular
      - web
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=top10db
    ports:
      - 5432:5432

volumes:
  postgres_data: 


